set names utf8;
drop database if exists roubintech;
create database roubintech charset=utf8;
use roubintech;

create table website(
    wid int primary key auto_increment,
    wgroup varchar(32),
    datahref varchar(128),
    icon varchar(64),
    wname varchar(32),
    isjump varchar(32),
    dataimg varchar(32)
);

insert into website values
(null,'_search','https://www.baidu.com/','#icon-CN_baidu','百&nbsp;度','',''),
(null,'_search','http://cn.bing.com/','#icon-bing','必&nbsp;应','',''),
(null,'_search','https://www.google.com.hk/','#icon-google','谷&nbsp;歌','_blank',''),
(null,'_shopping','https://www.jd.com/','#icon-jd01','京&nbsp;东','',''),
(null,'_shopping','https://www.taobao.com/','#icon-taobao','淘&nbsp;宝','',''),
(null,'_shopping','https://www.tmall.com/','#icon-tmall','天&nbsp;猫','',''),
(null,'_shopping','https://www.amazon.cn/','#icon-amazonsvg','亚马逊','_blank',''),
(null,'_shopping','http://www.dangdang.com/','#icon-dang','当&nbsp;当','',''),
(null,'_shopping','https://www.suning.com/','#icon-553859c69f894','苏&nbsp;宁','',''),
(null,'_shopping','https://www.dianping.com/','#icon-dianping','大众点评','',''),
(null,'_shopping','https://www.meituan.com/','#icon-meituan','美&nbsp;团','',''),
(null,'_social','http://weibo.com/','#icon-weibo','微&nbsp;博','','data-img="weibo"'),
(null,'_social','https://qzone.qq.com/','#icon-cntencentqzone','QQ空间','_blank',''),
(null,'_social','https://www.douban.com/','#icon-douban','豆&nbsp;瓣','','data-img="douban"'),
(null,'_social','https://wx.qq.com/','#icon-weixin','网页微信','_blank','data-img="weixin"'),
(null,'_social','https://tieba.baidu.com/','#icon-CN_baidutieba','百度贴吧','',''),
(null,'_social','https://www.zhihu.com/','#icon-footer_ico-zhihu','知&nbsp;乎','_blank','data-img="zhihu"'),
(null,'_social','http://www.jianshu.com/','#icon-daorujianshu','简&nbsp;书','_blank',''),
(null,'_social','https://twitter.com/','#icon-twitter','Twitter','_blank',''),
(null,'_social','https://www.facebook.com/','#icon-facebook','Facebook','_blank',''),
(null,'_video','http://www.youku.com/','#icon-cnyoukub','优&nbsp;酷','','data-img="youku"'),
(null,'_video','http://www.iqiyi.com/','#icon-aiqiyi','爱奇艺','','data-img="iqiyi"'),
(null,'_video','https://v.qq.com/','#icon-CN_tencentvideo','腾讯视频','',''),
(null,'_video','https://www.bilibili.com/','#icon-bilibili','bilibili','','data-img="bilibili"'),
(null,'_movie','https://movie.douban.com/','#icon-douban','豆瓣电影','_blank','data-img="doubanmovie"'),
(null,'_movie','http://www.bttiantangs.com/','sprite sprite-bttiantang','BT天堂','',''),
(null,'_movie','http://gaoqing.la/','sprite sprite-zhongguogaoqing','中国高清网','_blank',''),
(null,'_movie','http://subhd.com/','sprite sprite-subhd','Sub HD','','data-img="subhd"'),
(null,'_movie','http://assrt.net/','sprite sprite-weisheshou','射手字幕','',''),
(null,'_movie','http://www.zimuku.net/','sprite sprite-zimuku','字幕库','',''),
(null,'_music','http://music.163.com/','#icon-wangyiyun','网易音乐','_blank','data-img="wangyiyun"'),
(null,'_music','http://music.baidu.com/','#icon-changyonglogo48','百度音乐','',''),
(null,'_music','http://www.kugou.com/','#icon-kugou','酷&nbsp;狗','',''),
(null,'_music','https://y.qq.com/','#icon-QQyinle','QQ音乐','','data-img="qqmusic"'),
(null,'_music','http://www.xiami.com/','#icon-cnxiamicom','虾&nbsp;米','',''),
(null,'_music','http://www.ximalaya.com/','#icon-ximalaya','喜马拉雅','_blank','data-img="ximalaya"'),
(null,'_mail','http://mail.sina.com.cn/','#icon-icon_sina','新浪邮箱','',''),
(null,'_mail','http://email.163.com/','#icon-wangyi0','网易邮箱','',''),
(null,'_mail','https://mail.qq.com/','#icon-CN_tencent','QQ邮箱','',''),
(null,'_mail','http://mail.10086.cn/','#icon-139youxiang','139邮箱','_blank',''),
(null,'_mail','https://mail.google.com/','#icon-gmail','Gmail','_blank',''),
(null,'_mail','https://mail.live.com/','#icon-Microsoft_logo','微软邮箱','_blank',''),
(null,'_travel','http://www.ctrip.com/','#icon-xiecheng','携&nbsp;程','',''),
(null,'_travel','https://www.qunar.com/','#icon-qunaer','去哪儿','_blank',''),
(null,'_travel','http://www.ly.com/','#icon-cheng','同程旅游','',''),
(null,'_travel','http://www.tuniu.com/','#icon-tuniu-copy','途&nbsp;牛','_blank',''),
(null,'_travel','http://www.mafengwo.cn/','#icon-weibiaoti1','蚂蜂窝','',''),
(null,'_comic','http://www.ttmeiju.com/','sprite sprite-ttmeiju','天天美剧','','data-img="ttmeiju"'),
(null,'_comic','http://subhd.com/','sprite sprite-subhd','Sub HD','',''),
(null,'_comic','http://www.zimuzu.tv/','sprite sprite-zimuzu','YYeTs字幕组','',''),
(null,'_comic','http://share.dmhy.org/','sprite sprite-dmhy','动漫花园','','data-img="dmhy"'),
(null,'_comic','http://www.kisssub.org/','sprite sprite-ailiandongman','爱恋动漫','',''),
(null,'_comic','https://nyaso.com/','sprite sprite-miaosou','喵搜','','data-img="miaosou"'),
(null, "_download", "https://www.panc.cc/", "sprite sprite-pangci", "胖次", "", "data-img='pangci'"),
(null, "_download", "https://rarbg.is/torrents.php", "sprite sprite-rarbg", "RARBG", "_blank", "data-img='rarbg'");

select * from website;