set names utf8;
drop database if exists roubintech;
create database roubintech charset=utf8;
use roubintech;

create table website(
    wid int primary key auto_increment,
    wgroup varchar(32),
    datahref varchar(128),
    icon varchar(64),
    wname varchar(32),
    isjump varchar(32),
    dataimg varchar(32),
    img varchar(32)
);

insert into website values
(null,'_search','https://www.baidu.com/','#icon-CN_baidu','百度','','',''),
(null,'_search','http://cn.bing.com/','#icon-bing','必应','','',''),
(null,'_search','https://www.google.com.hk/','#icon-google','谷歌','_blank','',''),
(null,'_shopping','https://www.jd.com/','#icon-jd01','京东','','',''),
(null,'_shopping','https://www.taobao.com/','#icon-taobao','淘宝','','',''),
(null,'_shopping','https://www.tmall.com/','#icon-tmall','天猫','','',''),
(null,'_shopping','https://www.amazon.cn/','#icon-amazonsvg','亚马逊','_blank','',''),
(null,'_shopping','http://www.dangdang.com/','#icon-dang','当当','','',''),
(null,'_shopping','https://www.suning.com/','#icon-553859c69f894','苏宁','','',''),
(null,'_shopping','https://www.dianping.com/','#icon-dianping','大众点评','','',''),
(null,'_shopping','https://www.meituan.com/','#icon-meituan','美团','','',''),
(null,'_social','http://weibo.com/','#icon-weibo','微博','','data-img="weibo"','img/weibo.png'),
(null,'_social','https://qzone.qq.com/','#icon-cntencentqzone','QQ空间','_blank','',''),
(null,'_social','https://www.douban.com/','#icon-douban','豆瓣','','data-img="douban"','img/douban.png'),
(null,'_social','https://wx.qq.com/','#icon-weixin','网页微信','_blank','data-img="weixin"','img/weixin.png'),
(null,'_social','https://tieba.baidu.com/','#icon-CN_baidutieba','百度贴吧','','',''),
(null,'_social','https://www.zhihu.com/','#icon-footer_ico-zhihu','知乎','_blank','data-img="zhihu"','img/zhihu.png'),
(null,'_social','http://www.jianshu.com/','#icon-daorujianshu','简书','_blank','',''),
(null,'_social','https://twitter.com/','#icon-twitter','Twitter','_blank','',''),
(null,'_social','https://www.facebook.com/','#icon-facebook','Facebook','_blank','',''),
(null,'_video','http://www.youku.com/','#icon-cnyoukub','优酷','','data-img="youku"','img/youku.png'),
(null,'_video','http://www.iqiyi.com/','#icon-aiqiyi','爱奇艺','','data-img="iqiyi"','img/iqiyi.png'),
(null,'_video','https://v.qq.com/','#icon-CN_tencentvideo','腾讯视频','','',''),
(null,'_video','https://www.bilibili.com/','#icon-bilibili','bilibili','','data-img="bilibili"','img/bilibili.png'),
(null,'_movie','https://movie.douban.com/','sprite sprite-douban','豆瓣电影','_blank','data-img="doubanmovie"','img/doubanmovie.png'),
(null,'_movie','http://www.bttiantangs.com/','sprite sprite-bttiantang','BT天堂','','',''),
(null,'_movie','http://gaoqing.la/','sprite sprite-zhongguogaoqing','中国高清网','_blank','',''),
(null,'_movie','http://subhd.com/','sprite sprite-subhd','SubHD','','data-img="subhd"','img/subhd.png'),
(null,'_movie','http://assrt.net/','sprite sprite-weisheshou','射手字幕','','',''),
(null,'_movie','http://www.zimuku.net/','sprite sprite-zimuku','字幕库','','',''),
(null,'_music','http://music.163.com/','#icon-wangyiyun','网易音乐','_blank','data-img="wangyiyun"','img/wangyiyun.png'),
(null,'_music','http://music.baidu.com/','#icon-changyonglogo48','百度音乐','','',''),
(null,'_music','http://www.kugou.com/','#icon-kugou','酷狗','','',''),
(null,'_music','https://y.qq.com/','#icon-QQyinle','QQ音乐','','data-img="qqmusic"','img/qqmusic.png'),
(null,'_music','http://www.xiami.com/','#icon-cnxiamicom','虾米','','',''),
(null,'_music','http://www.ximalaya.com/','#icon-ximalaya','喜马拉雅','_blank','data-img="ximalaya"','img/ximalaya.png'),
(null,'_mail','http://mail.sina.com.cn/','#icon-icon_sina','新浪邮箱','','',''),
(null,'_mail','http://email.163.com/','#icon-wangyi0','网易邮箱','','',''),
(null,'_mail','https://mail.qq.com/','#icon-CN_tencent','QQ邮箱','','',''),
(null,'_mail','http://mail.10086.cn/','#icon-139youxiang','139邮箱','_blank','',''),
(null,'_mail','https://mail.google.com/','#icon-gmail','Gmail','_blank','',''),
(null,'_mail','https://mail.live.com/','#icon-Microsoft_logo','微软邮箱','_blank','',''),
(null,'_travel','http://www.ctrip.com/','#icon-xiecheng','携程','','',''),
(null,'_travel','https://www.qunar.com/','#icon-qunaer','去哪儿','_blank','',''),
(null,'_travel','http://www.ly.com/','#icon-cheng','同程旅游','','',''),
(null,'_travel','http://www.tuniu.com/','#icon-tuniu-copy','途牛','_blank','',''),
(null,'_travel','http://www.mafengwo.cn/','#icon-weibiaoti1','蚂蜂窝','','',''),
(null,'_comic','http://www.ttmeiju.com/','sprite sprite-ttmeiju','天天美剧','','data-img="ttmeiju"','img/ttmeiju.png'),
(null,'_comic','http://subhd.com/','sprite sprite-subhd','SubHD','','',''),
(null,'_comic','http://www.zimuzu.tv/','sprite sprite-zimuzu','YYeTs字幕组','','',''),
(null,'_comic','http://share.dmhy.org/','sprite sprite-dmhy','动漫花园','','data-img="dmhy"','img/dmhy.png'),
(null,'_comic','http://www.kisssub.org/','sprite sprite-ailiandongman','爱恋动漫','','',''),
(null,'_comic','https://nyaso.com/','sprite sprite-miaosou','喵搜','','data-img="miaosou"','img/miaosou.png'),
(null, "_download", "https://www.panc.cc/", "sprite sprite-pangci", "胖次", "", "data-img='pangci'",'img/pangci.png'),
(null, "_download", "https://rarbg.is/torrents.php", "sprite sprite-rarbg", "RARBG", "_blank", "data-img='rarbg'",'img/rarbg.png'),
(null, "_download", "https://www.torrentkitty.tv/search/", "sprite sprite-torrentkitty", "TorrentKitty", "_blank", "",''),
(null, "_download", "https://www.jiumodiary.com/", "sprite sprite-jiumodiary", "电子书", "", "data-img='jiumodiary'",'img/jiumodiary.png'),
(null, "_scholar", "http://xs.chongbuluo.com/scholar.html", "sprite sprite-google_scholar", "谷歌学术", "", "",''),
(null, "_scholar", "http://xs.bing.com/", "sprite sprite-biyingxueshu", "必应学术", "", "",''),
(null, "_scholar", "http://xueshu.baidu.com/", "sprite sprite-baidu", "百度学术", "", "",''),
(null, "_scholar", "http://scholar.cnki.net/", "sprite sprite-cnki", "CNKI学术", "", "",''),
(null, "_scholar", "http://trend.cnki.net/TrendSearch/", "sprite sprite-cnki", "CNKI学术趋势", "", "",''),
(null, "_scholar", "http://number.cnki.net/", "sprite sprite-cnki", "CNKI数字搜索", "", "",''),
(null, "_scholar", "http://s.wanfangdata.com.cn/Paper.aspx", "sprite sprite-wanfang", "万方数据", "", "",''),
(null, "_scholar", "http://www.oalib.com/", "sprite sprite-oalib", "OALib", "", "",''),
(null, "_scholar", "http://find.nlc.cn/", "sprite sprite-guotu", "国图文津", "_blank", "",''),
(null, "_scholar", "http://www.chaoxing.com/", "sprite sprite-chaoxing", "超星发现", "", "",''),
(null, "_scholar", "http://sou.library.sh.cn/", "sprite sprite-shangtufaxian", "上图发现", "", "",''),
(null, "_scholar", "http://www.sciinfo.cn/", "sprite sprite-zhongguoxueshu", "中国学术", "", "",''),
(null, "_scholar", "http://www.wdl.org/zh/", "sprite sprite-shijieshuzi", "世界数字图书", "", "",''),
(null, "_scholar", "http://www.las.ac.cn/", "sprite sprite-zhongkeyuan", "中科院文献", "", "",''),
(null, "_scholar", "http://s.sgst.cn/search/", "sprite sprite-sgst", "SGST上研检索", "", "",''),
(null, "_scholar", "http://pubmed.cn/", "sprite sprite-atugu", "PubMed", "", "",''),
(null, "_scholar", "http://web.mit.edu/search.html", "sprite sprite-mashengligong", "麻省理工文献", "", "",''),
(null, "_scholar", "https://www.repository.cam.ac.uk/discover", "sprite sprite-jianqiao", "剑桥大学知识库", "", "",''),
(null, "_scholar", "http://www.base-search.net/", "sprite sprite-bielefeld", "比勒费尔德学术", "", "",''),
(null, "_scholar", "http://www.duxiu.com/", "sprite sprite-souweixin", "读秀", "", "",''),
(null, "_scholar", "http://zju.summon.serialssolutions.com/#!/", "sprite sprite-zheda", "浙大图书馆", "", "",''),
(null, "_scholar", "http://pku.summon.serialssolutions.com/#!/", "sprite sprite-pku", "北大图书馆", "", "",''),
(null, "_scholar", "http://discovery.lib.tsinghua.edu.cn/primo_library/libweb/action/search.do", "sprite sprite-shuimu", "水木搜索", "", "",''),
(null, "_scholar", "http://repository.ust.hk/ir/Search/", "sprite sprite-xianggangdaxue", "香港大学文献", "_blank", "",''),
(null, "_scholar", "http://whu.findplus.cn/", "sprite sprite-luoqie", "珞珈学术", "", "",''),
(null, "_scholar", "http://www.zdic.net/", "sprite sprite-handian", "汉典", "", "",''),
(null, "_scholar", "http://www.open-open.com/doc/", "sprite sprite-open", "OPEN文档", "", "",''),
(null, "_scholar", "https://doaj.org/", "sprite sprite-doaj", "DOAJ", "", "",''),
(null, "_scholar", "http://jairo.nii.ac.jp/", "sprite sprite-jairo", "JAIRO", "", "",''),
(null, "_scholar", "http://ci.nii.ac.jp/", "sprite sprite-cinii", "CINII", "", "",''),
(null, "_scholar", "http://biorxiv.org/", "sprite sprite-br", "bioRxiv", "_blank", "",''),
(null, "_scholar", "http://ieeexplore.ieee.org/Xplore/home.jsp", "sprite sprite-ieee", "IEEE", "", "",''),
(null, "_scholar", "http://www.anychem.com/", "sprite sprite-huagong", "化工词典", "", "",''),
(null, "_scholar", "https://aminer.org/", "sprite sprite-aminer", "AMiner", "", "",''),
(null, "_scholar", "http://www.alldatasheetcn.com/", "sprite sprite-dianzi", "电子元件数据", "", "",''),
(null, "_design", "https://pixabay.com/", "sprite sprite-px", "Pixabay", "", "",''),
(null, "_design", "https://dribbble.com/", "sprite sprite-dribbble", "Dribbble", "_blank", "",''),
(null, "_design", "http://www.iconfont.cn/", "sprite sprite-iconfont", "IconFont", "_blank", "",''),
(null, "_design", "http://www.easyicon.net/", "sprite sprite-tubiao", "Easyicon", "", "",''),
(null, "_design", "http://www.colorhunt.co/", "sprite sprite-colorhunt", "Color Hunt", "", "",''),
(null, "_design", "http://colovely.nofach.com/", "sprite sprite-colovely", "Colovely", "", "",''),
(null, "_design", "http://colorrrs.com/", "sprite sprite-colorrrs", "Colorrrs", "", "",''),
(null, "_design", "http://stu.baidu.com/", "sprite sprite-baidu", "百度识图", "", "",''),
(null, "_design", "http://www.qiuziti.com/", "sprite sprite-qiuziti", "求字体", "", "",''),
(null, "_design", "http://vector.me/", "sprite sprite-vector", "Vector", "", "",''),
(null, "_design", "http://www.iconpng.com/", "sprite sprite-iconpng", "IconPng", "", "",''),
(null, "_design", "http://findicons.com/", "sprite sprite-findicon", "FindIcons", "", "",''),
(null, "_design", "http://www.iconarchive.com/", "sprite sprite-IconArchive", "IconArchive", "", "",''),
(null, "_design", "http://cn.freeimages.com/", "sprite sprite-freeimage", "FreeImages", "", "",''),
(null, "_design", "https://www.tineye.com/", "sprite sprite-tineye", "Tineye", "", "",''),
(null, "_design", "http://www.veryicon.com/", "sprite sprite-veryicon", "VeryIcon", "", "",''),
(null, "_design", "http://ui-cloud.com/", "sprite sprite-uicloud", "UICloud", "", "",''),
(null, "_design", "http://icongal.com/", "sprite sprite-icongallery", "IconGallery", "", "",''),
(null, "_design", "https://icons8.com/", "sprite sprite-icon8", "Icons8", "", "",''),
(null, "_data", "http://b1bj.com/", "sprite sprite-b1bj", "比一比价", "", "",''),
(null, "_data", "http://www.iso315.org/", "sprite sprite-fangwei", "防伪查询", "", "",''),
(null, "_data", "http://www.innojoy.com/search/index.shtml", "sprite sprite-miaosou", "专利检索", "", "",''),
(null, "_data", "http://www.tianyancha.com/", "sprite sprite-qiyexinxi", "企业信息查询", "", "",''),
(null, "_data", "http://app2.sfda.gov.cn/datasearchp/gzcxSearch.do", "sprite sprite-shipingyaoping", "食品药品", "", "",''),
(null, "_data", "http://db.yaozh.com/", "sprite sprite-yaozhi", "药智数据", "", "",''),
(null, "_data", "http://chs.so/", "sprite sprite-haiguan", "海关", "", "",''),
(null, "_data", "http://www.qgtong.com/so/Search.asp", "sprite sprite-haiguanbaisou", "海关百搜", "", "",''),
(null, "_data", "http://tongji.baidu.com/data/district", "sprite sprite-baidutongji", "百度统计", "", "",''),
(null, "_data", "http://index.baidu.com/", "sprite sprite-baidu", "百度指数", "", "",''),
(null, "_data", "http://data.weibo.com/index", "sprite sprite-miaosou", "微指数", "", "",''),
(null, "_data", "http://index.1688.com/", "sprite sprite-alizhishu", "阿里指数", "", "",''),
(null, "_data", "http://index.iqiyi.com/", "sprite sprite-miaosou", "爱奇艺指数", "", "",''),
(null, "_data", "http://datamodel.bitauto.com/", "sprite sprite-qichezhishu", "汽车指数", "", "",''),
(null, "_data", "http://www.umindex.com/", "sprite sprite-youmeng", "友盟指数", "", "",''),
(null, "_data", "http://www.talkingdata.com/index/#/mobileIndex/zh_cn", "sprite sprite-yidongguanxiang", "移动观象台", "", "",''),
(null, "_data", "http://data.stats.gov.cn/", "sprite sprite-guojia", "国家数据", "_blank", "",''),
(null, "_data", "http://www.cbooo.cn/", "sprite sprite-piaofang", "票房数据", "", "",''),
(null, "_data", "http://www.csres.com/", "sprite sprite-gb", "国家标准", "", "",''),
(null, "_data", "http://trends.baidu.com/ncee", "sprite sprite-baidu", "高考预测", "", "",''),
(null, "_data", "https://www.reg007.com/", "sprite sprite-zhuce", "注册过的网站", "_blank", "",''),
(null, "_data", "http://heat.qq.com/qianxi.php", "sprite sprite-tengxunbigdata", "腾讯位置大数据", "", "",''),
(null, "_data", "http://report.amap.com/", "sprite sprite-chengshijiaotong", "城市交通", "", "",''),
(null, "_data", "http://map.norsecorp.com/", "sprite sprite-wangluogongji", "网络攻击监测", "", "",''),
(null, "_data", "http://vis.360.cn/open/fishsite/", "sprite sprite-wangluozhapian", "网络诈骗监测", "", "",''),
(null, "_data", "http://openlaw.cn/", "sprite sprite-caipan", "裁判文书检索", "", "",''),
(null, "_data", "http://www.similarsitesearch.com/cn/", "sprite sprite-similarsite", "Similar Site", "", "",''),
(null, "_data", "http://data.worldbank.org.cn/", "sprite sprite-worldbank", "世界银行", "_blank", "",''),
(null, "_funny", "http://gzaas.com/", "sprite sprite-quanping", "全屏消息", "", "",''),
(null, "_funny", "http://cn.akinator.com/", "sprite sprite-shengdeng", "神灯猜人", "", "",''),
(null, "_funny", "http://deepba.com/", "sprite sprite-zhuangbi", "装逼神器", "", "",''),
(null, "_funny", "http://warin.space/", "sprite sprite-taikong", "太空激战", "", "",''),
(null, "_funny", "http://jokebird.com/", "sprite sprite-tunshi", "笑笑鸟", "_blank", "",''),
(null, "_funny", "http://slither.io/", "sprite sprite-tanchishe", "贪吃蛇", "", "",''),
(null, "_funny", "http://dazi.kukuw.com/", "sprite sprite-dazi", "在线打字", "", "",'');
select * from website;