set names utf8;
drop database if exists roubintech;
create database roubintech charset=utf8;
use roubintech;

create table website(
    wid int primary key auto_increment,
    wgroup varchar(32),
    datahref varchar(128),
    icon varchar(64),
    wname varchar(32),
    isjump varchar(32),
    dataimg varchar(32),
    img varchar(32),
    searchstring varchar(32)
);

insert into website values
(1, '_search', 'https://www.baidu.com/', '#icon-CN_baidu', '百度', '', '', '', '百度baidu'),
(2, '_search', 'http://cn.bing.com/', '#icon-bing', '必应', '', '', '', '必应bing'),
(3, '_search', 'https://www.google.com.hk/', '#icon-google', '谷歌', '_blank', '', '', '谷歌google'),
(4, '_shopping', 'https://www.jd.com/', '#icon-jd01', '京东', '', '', '', '京东jd'),
(5, '_shopping', 'https://www.taobao.com/', '#icon-taobao', '淘宝', '', '', '', '淘宝taobao'),
(6, '_shopping', 'https://www.tmall.com/', '#icon-tmall', '天猫', '', '', '', '天猫tmalltianmao'),
(7, '_shopping', 'https://www.amazon.cn/', '#icon-amazonsvg', '亚马逊', '_blank', '', '', '亚马逊amazonyamaxun'),
(8, '_shopping', 'http://www.dangdang.com/', '#icon-dang', '当当', '', '', '', '当当dangdang'),
(9, '_shopping', 'https://www.suning.com/', '#icon-553859c69f894', '苏宁', '', '', '', '苏宁suning'),
(10, '_shopping', 'https://www.dianping.com/', '#icon-dianping', '大众点评', '', '', '', '大众点评dianping'),
(11, '_shopping', 'https://www.meituan.com/', '#icon-meituan', '美团', '', '', '', '美团meituan'),
(12, '_social', 'http://weibo.com/', '#icon-weibo', '微博', '', 'data-img=\"weibo\"', 'img/weibo.png', '微博weibo'),
(13, '_social', 'https://qzone.qq.com/', '#icon-cntencentqzone', 'QQ空间', '_blank', '', '', 'QQ空间'),
(14, '_social', 'https://www.douban.com/', '#icon-douban', '豆瓣', '', 'data-img=\"douban\"', 'img/douban.png', '豆瓣douban'),
(15, '_social', 'https://wx.qq.com/', '#icon-weixin', '网页微信', '_blank', 'data-img=\"weixin\"', 'img/weixin.png', '网页微信weixin'),
(16, '_social', 'https://tieba.baidu.com/', '#icon-CN_baidutieba', '百度贴吧', '', '', '', '百度贴吧baidutieba'),
(17, '_social', 'https://www.zhihu.com/', '#icon-footer_ico-zhihu', '知乎', '_blank', 'data-img=\"zhihu\"', 'img/zhihu.png', '知乎zhihu'),
(18, '_social', 'http://www.jianshu.com/', '#icon-daorujianshu', '简书', '_blank', '', '', '简书jianshu'),
(19, '_social', 'https://twitter.com/', '#icon-twitter', 'Twitter', '_blank', '', '', 'Twitter推特'),
(20, '_social', 'https://www.facebook.com/', '#icon-facebook', 'Facebook', '_blank', '', '', 'Facebook脸书'),
(21, '_video', 'http://www.youku.com/', '#icon-cnyoukub', '优酷', '', 'data-img=\"youku\"', 'img/youku.png', '优酷youku'),
(22, '_video', 'http://www.iqiyi.com/', '#icon-aiqiyi', '爱奇艺', '', 'data-img=\"iqiyi\"', 'img/iqiyi.png', '爱奇艺aiqiyi'),
(23, '_video', 'https://v.qq.com/', '#icon-CN_tencentvideo', '腾讯视频', '', '', '', '腾讯视频qq'),
(24, '_video', 'https://www.bilibili.com/', '#icon-bilibili', 'bilibili', '', 'data-img=\"bilibili\"', 'img/bilibili.png', 'bilibili'),
(25, '_movie', 'https://movie.douban.com/', 'sprite sprite-douban', '豆瓣电影', '_blank', 'data-img=\"doubanmovie\"', 'img/doubanmovie.png', '豆瓣电影doubanmoviedianying'),
(26, '_movie', 'http://www.bttiantangs.com/', 'sprite sprite-bttiantang', 'BT天堂', '', '', '', 'BT天堂tiantang'),
(27, '_movie', 'http://gaoqing.la/', 'sprite sprite-zhongguogaoqing', '中国高清网', '_blank', '', '', '中国高清网zhongguogaoqing'),
(28, '_movie', 'http://subhd.com/', 'sprite sprite-subhd', 'SubHD', '', 'data-img=\"subhd\"', 'img/subhd.png', 'SubHD'),
(29, '_movie', 'http://assrt.net/', 'sprite sprite-weisheshou', '射手字幕', '', '', '', '射手字幕sheshouzimu'),
(30, '_movie', 'http://www.zimuku.net/', 'sprite sprite-zimuku', '字幕库', '', '', '', '字幕库zimuku'),
(31, '_music', 'http://music.163.com/', '#icon-wangyiyun', '网易音乐', '_blank', 'data-img=\"wangyiyun\"', 'img/wangyiyun.png', '网易音乐wangyiyinyuemusic163'),
(32, '_music', 'http://music.baidu.com/', '#icon-changyonglogo48', '百度音乐', '', '', '', '百度音乐baiduyinyuemusic'),
(33, '_music', 'http://www.kugou.com/', '#icon-kugou', '酷狗', '', '', '', '酷狗kugoumusic'),
(34, '_music', 'https://y.qq.com/', '#icon-QQyinle', 'QQ音乐', '', 'data-img=\"qqmusic\"', 'img/qqmusic.png', 'QQ音乐music'),
(35, '_music', 'http://www.xiami.com/', '#icon-cnxiamicom', '虾米', '', '', '', '虾米xiamimusic'),
(36, '_music', 'http://www.ximalaya.com/', '#icon-ximalaya', '喜马拉雅', '_blank', 'data-img=\"ximalaya\"', 'img/ximalaya.png', '喜马拉雅ximalayafm'),
(37, '_mail', 'http://mail.sina.com.cn/', '#icon-icon_sina', '新浪邮箱', '', '', '', '新浪邮箱sinamail'),
(38, '_mail', 'http://email.163.com/', '#icon-wangyi0', '网易邮箱', '', '', '', '网易邮箱wangyimail163'),
(39, '_mail', 'https://mail.qq.com/', '#icon-CN_tencent', 'QQ邮箱', '', '', '', 'QQ邮箱mail'),
(40, '_mail', 'http://mail.10086.cn/', '#icon-139youxiang', '139邮箱', '_blank', '', '', '139邮箱mail'),
(41, '_mail', 'https://mail.google.com/', '#icon-gmail', 'Gmail', '_blank', '', '', 'Gmail'),
(42, '_mail', 'https://mail.live.com/', '#icon-Microsoft_logo', '微软邮箱', '_blank', '', '', '微软邮箱livemail'),
(43, '_travel', 'http://www.ctrip.com/', '#icon-xiecheng', '携程', '', '', '', '携程xiecheng'),
(44, '_travel', 'https://www.qunar.com/', '#icon-qunaer', '去哪儿', '_blank', '', '', '去哪儿qunaer'),
(45, '_travel', 'http://www.ly.com/', '#icon-cheng', '同程旅游', '', '', '', '同程旅游lytongcheng'),
(46, '_travel', 'http://www.tuniu.com/', '#icon-tuniu-copy', '途牛', '_blank', '', '', '途牛tuniu'),
(47, '_travel', 'http://www.mafengwo.cn/', '#icon-weibiaoti1', '蚂蜂窝', '', '', '', '蚂蜂窝mafengwo'),
(48, '_comic', 'http://www.ttmeiju.com/', 'sprite sprite-ttmeiju', '天天美剧', '', 'data-img=\"ttmeiju\"', 'img/ttmeiju.png', '天天美剧ttmeiju'),
(49, '_comic', 'http://subhd.com/', 'sprite sprite-subhd', 'SubHD', '', '', '', 'SubHD'),
(50, '_comic', 'http://www.zimuzu.tv/', 'sprite sprite-zimuzu', 'YYeTs字幕组', '', '', '', 'YYeTs字幕组zimuzu'),
(51, '_comic', 'http://share.dmhy.org/', 'sprite sprite-dmhy', '动漫花园', '', 'data-img=\"dmhy\"', 'img/dmhy.png', '动漫花园dmhydongmanhuayuan'),
(52, '_comic', 'http://www.kisssub.org/', 'sprite sprite-ailiandongman', '爱恋动漫', '', '', '', '爱恋动漫ailiandongmankisssub'),
(53, '_comic', 'https://nyaso.com/', 'sprite sprite-miaosou', '喵搜', '', 'data-img=\"miaosou\"', 'img/miaosou.png', '喵搜miaosou'),
(54, '_download', 'https://www.panc.cc/', 'sprite sprite-pangci', '胖次', '', 'data-img=\'pangci\'', 'img/pangci.png', '胖次pangci'),
(55, '_download', 'https://rarbg.is/torrents.php', 'sprite sprite-rarbg', 'RARBG', '_blank', 'data-img=\'rarbg\'', 'img/rarbg.png', 'RARBG'),
(56, '_download', 'https://www.torrentkitty.tv/search/', 'sprite sprite-torrentkitty', 'TorrentKitty', '_blank', '', '', 'TorrentKitty'),
(57, '_download', 'https://www.jiumodiary.com/', 'sprite sprite-jiumodiary', '电子书', '', 'data-img=\'jiumodiary\'', 'img/jiumodiary.png', '电子书鸠摩jiumodiary'),
(58, '_scholar', 'http://xs.chongbuluo.com/scholar.html', 'sprite sprite-google_scholar', '谷歌学术', '', '', '', '谷歌学术googlescholar'),
(59, '_scholar', 'http://xs.bing.com/', 'sprite sprite-biyingxueshu', '必应学术', '', '', '', '必应学术bing'),
(60, '_scholar', 'http://xueshu.baidu.com/', 'sprite sprite-baidu', '百度学术', '', '', '', '百度学术baidu'),
(61, '_scholar', 'http://scholar.cnki.net/', 'sprite sprite-cnki', 'CNKI学术', '', '', '', 'CNKI学术'),
(62, '_scholar', 'http://trend.cnki.net/TrendSearch/', 'sprite sprite-cnki', 'CNKI学术趋势', '', '', '', 'CNKI学术趋势'),
(63, '_scholar', 'http://number.cnki.net/', 'sprite sprite-cnki', 'CNKI数字搜索', '', '', '', 'CNKI数字搜索'),
(64, '_scholar', 'http://s.wanfangdata.com.cn/Paper.aspx', 'sprite sprite-wanfang', '万方数据', '', '', '', '万方数据wanfangdata'),
(65, '_scholar', 'http://www.oalib.com/', 'sprite sprite-oalib', 'OALib', '', '', '', 'OALib'),
(66, '_scholar', 'http://find.nlc.cn/', 'sprite sprite-guotu', '国图文津', '_blank', '', '', '国图文津'),
(67, '_scholar', 'http://www.chaoxing.com/', 'sprite sprite-chaoxing', '超星发现', '', '', '', '超星发现chaoxing'),
(68, '_scholar', 'http://sou.library.sh.cn/', 'sprite sprite-shangtufaxian', '上图发现', '', '', '', '上图发现'),
(69, '_scholar', 'http://www.sciinfo.cn/', 'sprite sprite-zhongguoxueshu', '中国学术', '', '', '', '中国学术'),
(70, '_scholar', 'http://www.wdl.org/zh/', 'sprite sprite-shijieshuzi', '世界数字图书', '', '', '', '世界数字图书'),
(71, '_scholar', 'http://www.las.ac.cn/', 'sprite sprite-zhongkeyuan', '中科院文献', '', '', '', '中科院文献'),
(72, '_scholar', 'http://s.sgst.cn/search/', 'sprite sprite-sgst', 'SGST上研检索', '', '', '', 'SGST上研检索'),
(73, '_scholar', 'http://pubmed.cn/', 'sprite sprite-atugu', 'PubMed', '', '', '', 'PubMed'),
(74, '_scholar', 'http://web.mit.edu/search.html', 'sprite sprite-mashengligong', '麻省理工文献', '', '', '', '麻省理工文献mit'),
(75, '_scholar', 'https://www.repository.cam.ac.uk/discover', 'sprite sprite-jianqiao', '剑桥大学知识库', '', '', '', '剑桥大学知识库'),
(76, '_scholar', 'http://www.base-search.net/', 'sprite sprite-bielefeld', '比勒费尔德学术', '', '', '', '比勒费尔德学术'),
(77, '_scholar', 'http://www.duxiu.com/', 'sprite sprite-souweixin', '读秀', '', '', '', '读秀'),
(78, '_scholar', 'http://zju.summon.serialssolutions.com/#!/', 'sprite sprite-zheda', '浙大图书馆', '', '', '', '浙大图书馆'),
(79, '_scholar', 'http://pku.summon.serialssolutions.com/#!/', 'sprite sprite-pku', '北大图书馆', '', '', '', '北大图书馆'),
(80, '_scholar', 'http://discovery.lib.tsinghua.edu.cn/primo_library/libweb/action/search.do', 'sprite sprite-shuimu', '水木搜索', '', '', '', '水木搜索'),
(81, '_scholar', 'http://repository.ust.hk/ir/Search/', 'sprite sprite-xianggangdaxue', '香港大学文献', '_blank', '', '', '香港大学文献'),
(82, '_scholar', 'http://whu.findplus.cn/', 'sprite sprite-luoqie', '珞珈学术', '', '', '', '珞珈学术'),
(83, '_scholar', 'http://www.zdic.net/', 'sprite sprite-handian', '汉典', '', '', '', '汉典'),
(84, '_scholar', 'http://www.open-open.com/doc/', 'sprite sprite-open', 'OPEN文档', '', '', '', 'OPEN文档'),
(85, '_scholar', 'https://doaj.org/', 'sprite sprite-doaj', 'DOAJ', '', '', '', 'DOAJ'),
(86, '_scholar', 'http://jairo.nii.ac.jp/', 'sprite sprite-jairo', 'JAIRO', '', '', '', 'JAIRO'),
(87, '_scholar', 'http://ci.nii.ac.jp/', 'sprite sprite-cinii', 'CINII', '', '', '', 'CINII'),
(88, '_scholar', 'http://biorxiv.org/', 'sprite sprite-br', 'bioRxiv', '_blank', '', '', 'bioRxiv'),
(89, '_scholar', 'http://ieeexplore.ieee.org/Xplore/home.jsp', 'sprite sprite-ieee', 'IEEE', '', '', '', 'IEEE'),
(90, '_scholar', 'http://www.anychem.com/', 'sprite sprite-huagong', '化工词典', '', '', '', '化工词典'),
(91, '_scholar', 'https://aminer.org/', 'sprite sprite-aminer', 'AMiner', '', '', '', 'AMiner'),
(92, '_scholar', 'http://www.alldatasheetcn.com/', 'sprite sprite-dianzi', '电子元件数据', '', '', '', '电子元件数据'),
(93, '_design', 'https://pixabay.com/', 'sprite sprite-px', 'Pixabay', '', '', '', 'Pixabay'),
(94, '_design', 'https://dribbble.com/', 'sprite sprite-dribbble', 'Dribbble', '_blank', '', '', 'Dribbble'),
(95, '_design', 'http://www.iconfont.cn/', 'sprite sprite-iconfont', 'IconFont', '_blank', '', '', 'IconFont'),
(96, '_design', 'http://www.easyicon.net/', 'sprite sprite-tubiao', 'Easyicon', '', '', '', 'Easyicon'),
(97, '_design', 'http://www.colorhunt.co/', 'sprite sprite-colorhunt', 'Color Hunt', '', '', '', 'Color Hunt'),
(98, '_design', 'http://colovely.nofach.com/', 'sprite sprite-colovely', 'Colovely', '', '', '', 'Colovely'),
(99, '_design', 'http://colorrrs.com/', 'sprite sprite-colorrrs', 'Colorrrs', '', '', '', 'Colorrrs'),
(100, '_design', 'http://stu.baidu.com/', 'sprite sprite-baidu', '百度识图', '', '', '', '百度识图baidu'),
(101, '_design', 'http://www.qiuziti.com/', 'sprite sprite-qiuziti', '求字体', '', '', '', '求字体'),
(102, '_design', 'http://vector.me/', 'sprite sprite-vector', 'Vector', '', '', '', 'Vector'),
(103, '_design', 'http://www.iconpng.com/', 'sprite sprite-iconpng', 'IconPng', '', '', '', 'IconPng'),
(104, '_design', 'http://findicons.com/', 'sprite sprite-findicon', 'FindIcons', '', '', '', 'FindIcons'),
(105, '_design', 'http://www.iconarchive.com/', 'sprite sprite-IconArchive', 'IconArchive', '', '', '', 'IconArchive'),
(106, '_design', 'http://cn.freeimages.com/', 'sprite sprite-freeimage', 'FreeImages', '', '', '', 'FreeImages'),
(107, '_design', 'https://www.tineye.com/', 'sprite sprite-tineye', 'Tineye', '', '', '', 'Tineye'),
(108, '_design', 'http://www.veryicon.com/', 'sprite sprite-veryicon', 'VeryIcon', '', '', '', 'VeryIcon'),
(109, '_design', 'http://ui-cloud.com/', 'sprite sprite-uicloud', 'UICloud', '', '', '', 'UICloud'),
(110, '_design', 'http://icongal.com/', 'sprite sprite-icongallery', 'IconGallery', '', '', '', 'IconGallery'),
(111, '_design', 'https://icons8.com/', 'sprite sprite-icon8', 'Icons8', '', '', '', 'Icons8'),
(112, '_data', 'http://b1bj.com/', 'sprite sprite-b1bj', '比一比价', '', '', '', '比一比价'),
(113, '_data', 'http://www.iso315.org/', 'sprite sprite-fangwei', '防伪查询', '', '', '', '防伪查询'),
(114, '_data', 'http://www.innojoy.com/search/index.shtml', 'sprite sprite-miaosou', '专利检索', '', '', '', '专利检索'),
(115, '_data', 'http://www.tianyancha.com/', 'sprite sprite-qiyexinxi', '企业信息查询', '', '', '', '企业信息查询'),
(116, '_data', 'http://app2.sfda.gov.cn/datasearchp/gzcxSearch.do', 'sprite sprite-shipingyaoping', '食品药品', '', '', '', '食品药品'),
(117, '_data', 'http://db.yaozh.com/', 'sprite sprite-yaozhi', '药智数据', '', '', '', '药智数据'),
(118, '_data', 'http://chs.so/', 'sprite sprite-haiguan', '海关', '', '', '', '海关'),
(119, '_data', 'http://www.qgtong.com/so/Search.asp', 'sprite sprite-haiguanbaisou', '海关百搜', '', '', '', '海关百搜'),
(120, '_data', 'http://tongji.baidu.com/data/district', 'sprite sprite-baidutongji', '百度统计', '', '', '', '百度统计baidu'),
(121, '_data', 'http://index.baidu.com/', 'sprite sprite-baidu', '百度指数', '', '', '', '百度指数baidu'),
(122, '_data', 'http://data.weibo.com/index', 'sprite sprite-miaosou', '微指数', '', '', '', '微指数'),
(123, '_data', 'http://index.1688.com/', 'sprite sprite-alizhishu', '阿里指数', '', '', '', '阿里指数'),
(124, '_data', 'http://index.iqiyi.com/', 'sprite sprite-miaosou', '爱奇艺指数', '', '', '', '爱奇艺指数aiqiyi'),
(125, '_data', 'http://datamodel.bitauto.com/', 'sprite sprite-qichezhishu', '汽车指数', '', '', '', '汽车指数'),
(126, '_data', 'http://www.umindex.com/', 'sprite sprite-youmeng', '友盟指数', '', '', '', '友盟指数'),
(127, '_data', 'http://www.talkingdata.com/index/#/mobileIndex/zh_cn', 'sprite sprite-yidongguanxiang', '移动观象台', '', '', '', '移动观象台'),
(128, '_data', 'http://data.stats.gov.cn/', 'sprite sprite-guojia', '国家数据', '_blank', '', '', '国家数据'),
(129, '_data', 'http://www.cbooo.cn/', 'sprite sprite-piaofang', '票房数据', '', '', '', '票房数据'),
(130, '_data', 'http://www.csres.com/', 'sprite sprite-gb', '国家标准', '', '', '', '国家标准'),
(131, '_data', 'http://trends.baidu.com/ncee', 'sprite sprite-baidu', '高考预测', '', '', '', '高考预测'),
(132, '_data', 'https://www.reg007.com/', 'sprite sprite-zhuce', '注册过的网站', '_blank', '', '', '注册过的网站'),
(133, '_data', 'http://heat.qq.com/qianxi.php', 'sprite sprite-tengxunbigdata', '腾讯位置大数据', '', '', '', '腾讯位置大数据'),
(134, '_data', 'http://report.amap.com/', 'sprite sprite-chengshijiaotong', '城市交通', '', '', '', '城市交通'),
(135, '_data', 'http://map.norsecorp.com/', 'sprite sprite-wangluogongji', '网络攻击监测', '', '', '', '网络攻击监测'),
(136, '_data', 'http://vis.360.cn/open/fishsite/', 'sprite sprite-wangluozhapian', '网络诈骗监测', '', '', '', '网络诈骗监测'),
(137, '_data', 'http://openlaw.cn/', 'sprite sprite-caipan', '裁判文书检索', '', '', '', '裁判文书检索'),
(138, '_data', 'http://www.similarsitesearch.com/cn/', 'sprite sprite-similarsite', 'Similar Site', '', '', '', 'Similar Site'),
(139, '_data', 'http://data.worldbank.org.cn/', 'sprite sprite-worldbank', '世界银行', '_blank', '', '', '世界银行'),
(140, '_funny', 'http://gzaas.com/', 'sprite sprite-quanping', '全屏消息', '', '', '', '全屏消息'),
(141, '_funny', 'http://cn.akinator.com/', 'sprite sprite-shengdeng', '神灯猜人', '', '', '', '神灯猜人'),
(142, '_funny', 'http://deepba.com/', 'sprite sprite-zhuangbi', '装逼神器', '', '', '', '装逼神器'),
(143, '_funny', 'http://warin.space/', 'sprite sprite-taikong', '太空激战', '', '', '', '太空激战'),
(144, '_funny', 'http://jokebird.com/', 'sprite sprite-tunshi', '笑笑鸟', '_blank', '', '', '笑笑鸟'),
(145, '_funny', 'http://slither.io/', 'sprite sprite-tanchishe', '贪吃蛇', '', '', '', '贪吃蛇'),
(146, '_funny', 'http://dazi.kukuw.com/', 'sprite sprite-dazi', '在线打字', '', '', '', '在线打字');
select * from website;